version: '3.8'

networks:
  matrix-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password  # ✅ Ensures compatibility
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: x_matrix_db
      MYSQL_USER: x_matrix_user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - matrix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootPassword
    ports:
      - "9091:80"
    depends_on:
      - mysql
    networks:
      - matrix-network

  x-matrix-backend:
    build: .
    container_name: x-matrix-backend
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - matrix-network

volumes:
  mysql-data:
